//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: FunctionRpc.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate AzureFunctionsRpcMessages_FunctionRpcClient, then call methods of this protocol to make API calls.
internal protocol AzureFunctionsRpcMessages_FunctionRpcClientProtocol {
  func eventStream(callOptions: CallOptions?, handler: @escaping (AzureFunctionsRpcMessages_StreamingMessage) -> Void) -> BidirectionalStreamingCall<AzureFunctionsRpcMessages_StreamingMessage, AzureFunctionsRpcMessages_StreamingMessage>
}

internal final class AzureFunctionsRpcMessages_FunctionRpcClient: GRPCClient, AzureFunctionsRpcMessages_FunctionRpcClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the AzureFunctionsRpcMessages.FunctionRpc service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Bidirectional streaming call to EventStream
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func eventStream(callOptions: CallOptions? = nil, handler: @escaping (AzureFunctionsRpcMessages_StreamingMessage) -> Void) -> BidirectionalStreamingCall<AzureFunctionsRpcMessages_StreamingMessage, AzureFunctionsRpcMessages_StreamingMessage> {
    return self.makeBidirectionalStreamingCall(path: "/AzureFunctionsRpcMessages.FunctionRpc/EventStream",
                                               callOptions: callOptions ?? self.defaultCallOptions,
                                               handler: handler)
  }

}

/// To build a server, implement a class that conforms to this protocol.
internal protocol AzureFunctionsRpcMessages_FunctionRpcProvider: CallHandlerProvider {
  func eventStream(context: StreamingResponseCallContext<AzureFunctionsRpcMessages_StreamingMessage>) -> EventLoopFuture<(StreamEvent<AzureFunctionsRpcMessages_StreamingMessage>) -> Void>
}

extension AzureFunctionsRpcMessages_FunctionRpcProvider {
  internal var serviceName: String { return "AzureFunctionsRpcMessages.FunctionRpc" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "EventStream":
      return BidirectionalStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return self.eventStream(context: context)
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload` for request and response messages
extension AzureFunctionsRpcMessages_StreamingMessage: GRPCProtobufPayload {}

